services:
    _defaults:
        autowire: true
        public: true

    david63.autotopicsubscribe.listener:
        class: david63\autotopicsubscribe\event\listener
        tags:
            - { name: event.listener }
